spring:
  application:
    name: springsecuritydemo

  security:
    user:
      name: demo
      password: demo123
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

server:
  port: 8081